# WGOM Atlantic Cod Numbers at age

**Description**: 

Historical numbers at age (mean).  Depending on 
the timing of the most recent stock assessment, these contain a mix of 
assessment estimates and a "bridge" to current regulatory year. The bridging is
performed in a manner consistent with the stock projections, but may be updated with
realized commercial and recreational removals. 

Simulated Numbers-at-Age for Western Gulf of Maine Cod for the upcoming regulatory cycle.

**Years available**: 

Mean historical numbers at age are provided for the most recent 3 years.  

Projected numbers at age are provided for the upcoming management year.


## Methods

### Data sources

All are derived from the most recent stock assessment ([2024 Management Track](https://apps-st.fisheries.noaa.gov/sis/docServlet?fileAction=download&fileId=10095))
that was used for providing specifications advice to fishery managers

### Data extraction 

Inputs need for stock assessment were obtained from stock assessment scientists. 
This includes the "WHAM" model file  and an ASAP3 model file.

### Data analysis/Processing

[Data processing code](https://github.com/kimberly-bastille/groundfishRDM/blob/main/Code/pre_sim/get_cod_assessment_data.R) can be seen in the groundfishRDM repository. In brief, for 2026 fishery management, we

1.  We use using actual catch (in mt) for 2023 and 2024. We use 75%FMSY for 2025-2026 mortality.
2.  We project the stock forward and extract mean NAA through 2025.
3.  We simulate 500 draws of the Numbers-at-Age for each age class for 2026 based on 
the mean and standard deviations from WHAM.

