# GOM Haddock Numbers at age


**Description**: 

Mean historical numbers at age.

Simulated future numbers at age for Western Gulf of Maine Cod.

**Years available**: 

Mean historical numbers at age are provided through "this year."  

Projected numbers at age are provided for the upcoming management year.


## Methods

### Data sources

All are derived from the most recent stock assessment ([2024 Management Track](https://apps-st.fisheries.noaa.gov/sis/docServlet?fileAction=download&fileId=9882))
that was used for providing specifications advice to fishery managers

### Data extraction 

Inputs need for stock assessment were obtained from stock assessment scientists. 
This includes the "WHAM" model file weight-at-age excel file.

### Data analysis/Processing

[Data processing code](https://github.com/kimberly-bastille/groundfishRDM/blob/main/Code/pre_sim/get_haddock_assessment_data.R) can be seen in the groundfishRDM repository. In brief, for 2026 fishery management, we

1.  We use using actual catch (in mt) for 2023 and 2024. We use 75%FMSY for 2025-2026 mortality.
2.  We project the stock forward and extract mean NAA through 2025.
3.  We simulate 500 draws of the Numbers-at-Age for each age class for 2026.


